# Generated by Django 3.1 on 2020-10-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200921_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='network.post'),
        ),
    ]
